### ISSUE TITLE
issues with Python process for parallel upload

### ISSUE THREAD

**Issue by gilv** [IBM/data-pre-processing-with-pywren#16]
Unfortunately i am getting "too many open files" when trying to upload images into COS.
I will remove process () and we will do it sequentially. Perhaps at later stage we need to use Python's Pool module so it will better handle uploads of images in COS.

**Comment by pvaneck** [comment]
That's odd, I have not been able to recreate the error and have been uploading fine.
I can adjust the code to use a Pool with a limited number of worker processes to see if that helps, as having some level of multiprocessing for the upload really speeds things up.

**Comment by gilv** [comment]
@pvaneck i run previous code, from my laptop. I might think it was an issue in my local Jupyter notebook with some local configuration. So you managed to use previous code with Process and upload 1050 images from lfw-a data set without issues?? If yes, it's great... then may be we need to remove #17  (it was merged already )
@rhagarty FYI

**Comment by pvaneck** [comment]
@gilv Ah, so you were running locally. That might explain why I am not hitting it, as I have always been  uploading from the notebook in Watson Studio. All 1054 images generally took under a minute to upload with the old code.

I can go ahead and adjust it to use a Pool anyway to avoid creating too many processes.
